### ISSUE TITLE
Cannot mount the same path in different services

### ISSUE THREAD

**Issue by tusooa** [mikebarkmin/docker-volume-glusterfs#8]
If we mount a volume that has the same underlying path as another one, it complains.

POC:
```
USER@HOST1:~/testgluster$ sudo docker-compose up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "testgluster_default" with the default driver
Creating testgluster_alpine1_1 ... done
USER@HOST1:~/testgluster$ cat docker-compose.yaml
version: '3'
services:
  alpine1:
    image: alpine
    volumes:
      - foo:/mnt/foo
    entrypoint: 'ping docker.com'

volumes:
  foo:
    driver: glusterfs:latest
    driver_opts:
      servers: HOST2
      volname: gv0
      subdir: foo
USER@HOST1:~/testgluster$ cd nginx1
USER@HOST1:~/testgluster/nginx1$ cat docker-compose.yaml
version: '3'
services:
  alpine2:
    image: nginx:latest
    volumes:
      - foo4:/mnt/foo/bar
    entrypoint: 'ping docker.com'

volumes:
  foo4:
    driver: glusterfs:latest
    driver_opts:
      servers: HOST2
      volname: gv0
      subdir: foo
USER@HOST1:~/testgluster/nginx1$ sudo docker-compose up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "nginx1_default" with the default driver
Creating nginx1_alpine2_1 ... error

ERROR: for nginx1_alpine2_1  Cannot start service alpine2: error while mounting volume '': VolumeDriver.Mount: glusterfs command execute failed: exit status 32 (/sbin/mount.glusterfs: according to mtab, GlusterFS is already mounted on /mnt/volumes/1d1cd74a75953d38a0665044f2c29a3f/acbd18db4cc2f85cedef654fccc4a4d8
)

ERROR: for alpine2  Cannot start service alpine2: error while mounting volume '': VolumeDriver.Mount: glusterfs command execute failed: exit status 32 (/sbin/mount.glusterfs: according to mtab, GlusterFS is already mounted on /mnt/volumes/1d1cd74a75953d38a0665044f2c29a3f/acbd18db4cc2f85cedef654fccc4a4d8
)
ERROR: Encountered errors while bringing up the project.
```

**Comment by aqos156** [comment]
@tusooa I have ran into a similar issue in our pre production deployment, with a small twist. It deleted the contents of the whole volume...  I do not have exact files, but i can try to recreate what happened.

Imagine you have two stacks A and B.

Stack A
```yml
version: '3.8'
services: 
  alpine2:
    image: nginx:latest
    volumes:
      - test-volume:/mnt/foo/bar
    entrypoint: 'ping docker.com'

volumes:
  test-volume:
    driver: glusterfs:latest
    driver_opts:
      volname: gv0
      subdir: foo
```

And a stack B:
```yml
version: '3.8'
services: 
  alpine2:
    image: nginx:latest
    volumes:
      - test-volume_different_docker_volume_name:/mnt/foo/bar
    entrypoint: 'ping docker.com'

volumes:
  test-volume_different_docker_volume_name: #Notice the difference in docker volume name from Stack A
    driver: glusterfs:latest
    driver_opts:
      volname: gv0
      subdir: foo
```

If you deploy Stack A and Stack B (notice the different docker volume name) the stack A starts successfully, but stack B fails with same error message as in this issue. If you try to remove the stack it fails on volume removal and if you try to remove the volume `test-volume_different_docker_volume_name` directly it also fails but this time it deletes contents of the whole gluster volume - gv0 becomes **empty**.

I do not have any experience of writing volume plugins, but from what I could find digging through how volume plugins work and this source code it seems that docker inits the mount of the volume from Stack A -> Success. Then it tries to mount the volume from Stack B, but it is already mounted within the driver plugin so it fails but also keeps the instance of the volume  (`docker volume ls` shows the volume test-volume_different_docker_volume_name). If then a `docker rm` is issued it probably somehow thinks the volume is unmounted and calls https://github.com/mikebarkmin/docker-volume-glusterfs/blob/master/main.go#L148 on the whole mounted GFS volume `gv0`. As I said, I have never developed any volume plugins, so I might be completely wrong.

We have a temporary workaround in place where we have 2 same kinds of volume plugins - glusterfs:v7 and glusterfs:v7-for-backup. This resolves the issue for our use case.

@mikebarkmin also wanted to ask you if there will be any development or maintenance on this plugin? From what I found the official gfs plugin is unmaintained and this is probably the best one out there from our testing.
